### ISSUE TITLE
`IOException: Unexpected end of stream` on proxy request after period of inactivity

### ISSUE THREAD

**Issue by fvennetier** [open-io/oio-api-java#29]
After some period of inactivity, it seems that a connection can be reused after it has been closed server-side, leading to `IOException: Unexpected end of stream`. Following is a shortened stack trace.
```
2016-12-07 10:54:12 Failed to perform request
io.openio.sds.exceptions.OioSystemException: Http request execution error
    at io.openio.sds.http.OioHttp$RequestBuilder.execute(OioHttp.java:235)
    at io.openio.sds.http.OioHttp$RequestBuilder.execute(OioHttp.java:191)
    at io.openio.sds.proxy.ProxyClient.getObjectInfo(ProxyClient.java:711)
    at io.openio.sds.DefaultClient.getObjectInfo(DefaultClient.java:169)
    at io.openio.sds.DefaultClient.getObjectInfo(DefaultClient.java:162)
    
...

Caused by: java.io.IOException: Unexpected end of stream
    at io.openio.sds.http.OioHttpResponse.read(OioHttpResponse.java:125)
    at io.openio.sds.http.OioHttpResponse.next(OioHttpResponse.java:108)
    at io.openio.sds.http.OioHttpResponse.readHeaders(OioHttpResponse.java:101)
    at io.openio.sds.http.OioHttpResponse.responseHead(OioHttpResponse.java:91)
    at io.openio.sds.http.OioHttpResponse.build(OioHttpResponse.java:46)
    at io.openio.sds.http.OioHttp$RequestBuilder.readResponse(OioHttp.java:255)
    at io.openio.sds.http.OioHttp$RequestBuilder.execute(OioHttp.java:214)
    ... 11 more
```

**Comment by jkasarherou** [comment]
what should be correct behavior? detect such failure and remove connection from the pool?

**Comment by fvennetier** [comment]
I did not dig into the code at the moment, but yes, there should be a mechanism to verify that a connection is still active before trying to reuse it.

This bug is harmless though, the reporter told me that the upper level was properly retrying the request. It's just a bit annoying to see the stack trace in the logs.
