### ISSUE TITLE
getNamespaceInfo(): Expected BEGIN_OBJECT but was STRING

### ISSUE THREAD

**Issue by gdelaporte** [open-io/oio-api-java#41]
While using this code:

```
package it.customer.prova.openio.api;
import io.openio.sds.Client;
import io.openio.sds.ClientBuilder;
import io.openio.sds.models.NamespaceInfo;

public class GetNamespaceInfo {

    public static void main(String[] args) {
        Client client = ClientBuilder.newClient("OPENIO", "http://192.168.99.100:6007");

        NamespaceInfo namespace = client.getNamespaceInfo();
    }

}
```

We got the following error:

```
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
    at com.google.gson.Gson.fromJson(Gson.java:861)
    at io.openio.sds.http.Verifiers.extractError(Verifiers.java:144)
    at io.openio.sds.http.Verifiers.access$000(Verifiers.java:26)
    at io.openio.sds.http.Verifiers$4.verify(Verifiers.java:105)
    at io.openio.sds.http.OioHttp$RequestBuilder.execute(OioHttp.java:217)
    at io.openio.sds.http.OioHttp$RequestBuilder.execute(OioHttp.java:191)
    at io.openio.sds.http.OioHttp$RequestBuilder.execute(OioHttp.java:240)
    at io.openio.sds.proxy.ProxyClient.getNamespaceInfo(ProxyClient.java:135)
    at io.openio.sds.DefaultClient.getNamespaceInfo(DefaultClient.java:55)
    at it.customer.prova.openio.api.GetNamespaceInfo.main(GetNamespaceInfo.java:11)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
```

It seems that the JSON return by `getNamespaceInfo()` is not matching anymore.

**Comment by claudiosignorini** [comment]
Sniffing the http req/resp with a proxy I see:

Request:

```
GET /v3.0/OPENIO/conscience/info HTTP/1.1
Accept: */*
Connection: keep-alive
User-Agent: oio-http
Host: 192.168.99.100:6007
Accept-Encoding: gzip, deflate
Content-Length: 0
```

Response:

```
<html><h1>Bad Request</h1><p>The server could not comply with the request since it is either malformed or otherwise incorrect.</p></html>
```

I'm using the doker image as server.
Thanks!

Claudio

**Comment by fvennetier** [comment]
`192.168.99.100:6007` is the endpoint of the swift proxy. With the docker image, `oio-proxy` is listening on port **6006**.
